version: '3.8'

volumes:
  backend:

services:
  prontogram_service:
    hostname: service.prontogram
    container_name: prontogram_service
    build:
      context: .
      dockerfile: ./backend.Dockerfile
    env_file:
      - .env
    ports:
      - "${PRONTOGRAM_SERVICE_PORT}:8080"
    networks:
      - prontogram
    restart: unless-stopped
  
  prontogram_swagger:
    hostname: swagger.prontogram
    container_name: prontogram_swagger
    build:
      context: .
      dockerfile: ./swagger.Dockerfile
      args:
        - PRONTOGRAM_SERVICE_HOST=${PRONTOGRAM_SERVICE_HOST}
    env_file:
      - .env
    ports:
      - "$PRONTOGRAM_SWAGGER_PORT:8080"
    networks:
      - prontogram
    restart: unless-stopped
    depends_on:
      - prontogram_service
networks:
  prontogram:
    driver: bridge
    name: prontogram-net
