basePath: /api/v1
definitions:
  entities.Airport:
    properties:
      airport_id:
        type: string
      city:
        type: string
      name:
        type: string
    type: object
  entities.CustomerFlightSubscriptionRequest:
    properties:
      airport_id_destination:
        type: string
      airport_id_origin:
        type: string
      customer_prontogram_id:
        type: string
      travel_date_end:
        description: end travel date range in ISO 8601 format (with timezone UTC)
        type: string
      travel_date_start:
        description: start travel date range in ISO 8601 format (with timezone UTC)
        type: string
      travel_max_price:
        type: number
      travel_seats_count:
        type: integer
    type: object
  flight_subscription.ResError:
    properties:
      error:
        type: string
    type: object
externalDocs:
  description: OpenAPI
  url: https://swagger.io/resources/open-api/
host: localhost:8090
info:
  contact:
    email: support@swagger.io
    name: API Support
    url: http://www.swagger.io/support
  description: This is an API specification for the ACMESKy services.
  license:
    name: MIT
    url: https://opensource.org/license/mit
  termsOfService: http://swagger.io/terms/
  title: ACMESky Swagger API
  version: "1.0"
paths:
  /airports:
    get:
      consumes:
      - application/json
      description: Get a list of all available airports
      parameters:
      - description: Search query
        in: query
        name: query
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              items:
                $ref: '#/definitions/entities.Airport'
              type: array
            type: array
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/flight_subscription.ResError'
      summary: Get all airports
      tags:
      - airport
  /subscribe:
    post:
      consumes:
      - application/json
      description: Add a Travel preference and subscribe to notification service
      parameters:
      - description: subscription data
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/entities.CustomerFlightSubscriptionRequest'
      responses:
        "200":
          description: OK
          schema:
            type: string
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/flight_subscription.ResError'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/flight_subscription.ResError'
      summary: Add a Travel preference
      tags:
      - travel_preference
swagger: "2.0"
