services:
  acmesky_db:
    hostname: db.acmesky
    container_name: acmesky_mysql_container
    build: ./
    env_file:
      - .env
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - "5432:5432"
      - "3306:3306"
    networks:
      - acmesky
    restart: unless-stopped

  # temp for dev
  phpmyadmin:
    container_name: phpmyadmin_container
    image: phpmyadmin
    restart: unless-stopped
    ports:
      - 8060:80
    networks:
      - acmesky
    environment:
      - PMA_HOSTS=db.acmesky
    depends_on:
      - acmesky_db

networks:
  acmesky:
    driver: bridge
    name: acmesky-net

volumes:
  mysql_data:
