services:
  db:
    image: postgres
    restart: always
    ports:
      - 5434:5432
    environment:
      POSTGRES_USER: acmebank
      POSTGRES_PASSWORD: acmebank

  adminer:
    image: adminer
    restart: always
    ports:
      - 9080:8080

  # bank:
  #   build: .
  #   ports:
  #     - "8000:8000"
