image: python:3.8-buster

before_script:
  - pip install -r requirements.txt

pages:
  stage: deploy
  script:
  - mkdocs build --strict --verbose
  - mv site public
  artifacts:
    paths:
    - site
  only:
    - main
