image: python:3.8-buster

pages:
  image: golang:latest
  stage: pages
  before_script:
    - pip install -r requirements.txt
  script:
  - go install -v github.com/swaggo/swag/cmd/swag@v1.16.3
  - cd src/ACMESkyNCC/middleware
  - swag init --parseDependency --instanceName ncc
  - cd ../../ACMESkyService
  - swag init --parseDependency --instanceName acme
  - cd ../BankService/server
  - swag init --parseDependency --instanceName bank
  - cd ../../FlightCompanyService
  - swag init --parseDependency --instanceName fc
  - cd ../GeoDistance
  - swag init --parseDependency --instanceName geo
  - mkdocs build --strict --verbose
  - mv site public
  artifacts:
    paths:
    - public
  only:
    - main
