networks:
  flightcompany_backend:
    name: "flightcompany_backend"
  flightcompany_public:
    name: "net"
    external: true

services:
  #  adminer:
  #    container_name: adminer_flightcompany
  #    image: adminer
  #    restart: unless-stopped
  #    ports:
  #      - 8099:8080
  #    networks:
  #      - flightcompany_backend
  #      - flightcompany_public

  flightcompany_db:
    hostname: db.flightcompany
    container_name: flightcompany_mysql_container
    build: ./src/FlightCompanyDB/.
    image: flightcompany/db
    env_file:
      - ./src/FlightCompanyDB/.env
    ports:
      - "5433:5432"
      - "3307:3306"
    networks:
      - flightcompany_backend
    restart: unless-stopped
  flightcompany_service:
    depends_on:
      - flightcompany_db
    hostname: service.flightcompany
    container_name: flightcompany_service_container
    build: ./src/FlightCompanyService/.
    image: flightcompany/service
    env_file:
      - ./src/FlightCompanyService/.env
    ports:
      - "8091:8091"
    networks:
      - flightcompany_backend
      - flightcompany_public
    restart: unless-stopped
