site_name: ACMESky Docs
site_author: Luca Bassi, Gabriele Genovese, Jacopo Rimediotti
repo_name: expuss2000/acmesky
repo_url: https://gitlab.com/expuss2000/acmesky
theme:
  logo: assets/airplane.svg
  favicon: assets/airplane.svg
  name: material
  palette:
    # Palette toggle for automatic mode
    - media: "(prefers-color-scheme)"
      primary: deep purple
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode

    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      primary: deep purple
      scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      primary: deep purple
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to system preference

markdown_extensions:
  - pymdownx.arithmatex:
      generic: true

extra_javascript:
  - javascripts/katex.js
  - javascripts/katex.min.js
  - javascripts/auto-render.min.js

extra_css:
  - stylesheets/katex.min.css
  - stylesheets/extra.css
