site_name: ACMESky Docs
site_author: Luca Bassi, Gabriele Genovese, Jacopo Rimediotti
repo_name: expuss2000/acmesky
repo_url: https://gitlab.com/expuss2000/acmesky
theme:
  logo: assets/airplane.svg
  favicon: assets/airplane.svg
  name: material
  palette:
    primary: deep purple
    scheme: slate

markdown_extensions:
  - pymdownx.arithmatex:
      generic: true

extra_javascript:
  - javascripts/katex.js
  - javascripts/katex.min.js
  - javascripts/auto-render.min.js

extra_css:
  - stylesheets/katex.min.css
  - stylesheets/extra.css

plugins:
  - render_swagger:
      allow_arbitrary_locations : true
      css: https://acmesky-expuss2000-d511ae4437280f0ac43140f188bc34fa077888571f00.gitlab.io/stylesheets/swagger-ui.css