basePath: /
definitions:
  main.ResBody:
    properties:
      distance:
        type: string
      status:
        type: string
      value:
        type: integer
    type: object
info:
  contact:
    email: gabriele.genovese2@studio.unibo.it
    name: Gabriele Genovese
  description: This is a microservice to calculate the distance between two points.
  license:
    name: GPLv2
    url: https://www.gnu.org/licenses/old-licenses/gpl-2.0.html
  title: Geographical Distance Service API
  version: "1.0"
paths:
  /distance:
    get:
      consumes:
      - application/json
      description: Given two locations, it responds with the distance.
      parameters:
      - description: From location
        in: query
        name: from
        required: true
        type: string
      - description: To location
        in: query
        name: to
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/main.ResBody'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/main.ResBody'
      summary: Calculate a distance between two locations
      tags:
      - main
swagger: "2.0"
