basePath: /
definitions:
  entities.Airport:
    properties:
      airport_id:
        example: "5"
        type: string
      city:
        example: Bologna
        type: string
      name:
        example: Aeroporto di Bologna-Guglielmo Marconi
        type: string
    type: object
  entities.Flight:
    properties:
      airport_destination_id:
        example: "20"
        type: string
      airport_origin_id:
        example: "5"
        type: string
      arrival_datetime:
        example: "2024-01-10 05:30:00"
        type: string
      available_seats_count:
        example: 2
        type: integer
      depart_datetime:
        example: "2024-01-01 14:00:00"
        type: string
      flight_id:
        example: "1"
        type: string
      flight_price:
        example: 199.99
        type: number
    type: object
  entities.FlightBooking:
    properties:
      booking_id:
        example: 101
        type: integer
      customer_name:
        example: Mario
        type: string
      customer_surname:
        example: Rossi
        type: string
      flight_id:
        example: 2
        type: integer
      passengers_count:
        example: 2
        type: integer
    type: object
externalDocs:
  description: OpenAPI
  url: https://swagger.io/resources/open-api/
host: localhost:8091
info:
  contact:
    email: support@swagger.io
    name: API Support
    url: http://www.swagger.io/support
  description: This is an API specification for the FlightCompany services.
  license:
    name: MIT
    url: https://opensource.org/license/mit
  termsOfService: http://swagger.io/terms/
  title: FlightCompany Swagger API
  version: "1.0"
paths:
  /airports:
    get:
      description: Get a list of all available airports
      parameters:
      - description: Search string to return airports which names contains this substring
        in: query
        name: query
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/entities.Airport'
            type: array
        "500":
          description: Internal Server Error
      summary: Get all airports
      tags:
      - Airports
  /bookings/:
    post:
      description: book a flight which can be confirmed or unbooked
      parameters:
      - description: ID of origin airport from GET /airports
        in: query
        name: origin_airport
        required: true
        type: string
      - description: ID of destination airport from GET /airports
        in: query
        name: dest_airport
        required: true
        type: string
      - description: number > 0 of min passengers seats count that need be available
        in: query
        name: passengers_count
        required: true
        type: number
      - description: string rappresenting the datetime for start filter range
        in: query
        name: start_range_datetime
        required: true
        type: string
      - description: string rappresenting the datetime for end filter range
        in: query
        name: end_range_datetime
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: Flight has been booked
          schema:
            items:
              $ref: '#/definitions/entities.FlightBooking'
            type: array
        "400":
          description: If provided booking is in wrong format
        "500":
          description: If any error occurred
      summary: Book a flight
      tags:
      - Bookings
  /bookings/{bookingID}:
    delete:
      description: Unbook a booked flight
      parameters:
      - description: A booking ID
        in: path
        name: bookingID
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: Flight has been unbooked
        "400":
          description: If booking has not been provided
        "404":
          description: If booking doesn't exist
        "500":
          description: If any error occurred and flight has not been unbooked
      summary: Unbook a flight
      tags:
      - Bookings
  /bookings/{bookingID}/confirm:
    post:
      description: Confirm / pay a booking of flight which was not unconfirmed yet
      parameters:
      - description: A booking ID
        in: path
        name: bookingID
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: Booking has been confirmed
        "400":
          description: If booking has not been provided
        "404":
          description: If booking doesn't exist
        "500":
          description: If any error occurred and flight has not been confirmed
      summary: Confirm a booking
      tags:
      - Bookings
  /flights:
    get:
      description: Get a list of all available flights over thr provided filters
      parameters:
      - description: ID of origin airport from GET /airports
        in: query
        name: origin_airport
        required: true
        type: string
      - description: ID of destination airport from GET /airports
        in: query
        name: dest_airport
        required: true
        type: string
      - description: number > 0 of min passengers seats count that need be available
        in: query
        name: passengers_count
        required: true
        type: number
      - description: string rappresenting the datetime for start filter range
        in: query
        name: start_range_datetime
        required: true
        type: string
      - description: string rappresenting the datetime for end filter range
        in: query
        name: end_range_datetime
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/entities.Flight'
            type: array
        "400":
          description: Bad Request
        "500":
          description: Internal Server Error
      summary: Get all filtered flights
      tags:
      - Flight
swagger: "2.0"
