services:
  middleware:
    hostname: service.ncc
    container_name: ncc_middleware
    build: ./middleware
    restart: unless-stopped
    ports:
      - "8088:8089"
  backend:
    container_name: ncc_backend
    build: ./backend
    restart: unless-stopped
    ports:
      - "8000:8000"
      - "8001:8001"
