name: gendocs

on:
  push:
    branches:
      - master 
      - main
      
permissions:
  contents: write
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Configure Git Credentials
        run: |
          git config user.name github-actions[bot]
          git config user.email 41898282+github-actions[bot]@users.noreply.github.com
      - uses: actions/setup-python@v5
        with:
          python-version: 3.x
      - run: echo "cache_id=$(date --utc '+%V')" >> $GITHUB_ENV 
      - uses: actions/cache@v4
        with:
          key: mkdocs-material-${{ env.cache_id }}
          path: .cache
          restore-keys: |
            mkdocs-material-
      - run: pip install -r requirements.txt
      - run: apt install golang
      - run: go install -v github.com/swaggo/swag/cmd/swag@latest
      - run: cd src/ACMESkyNCC/middleware
      - run: swag init --parseDependency --instanceName ncc
      - run: cd ../../ACMESkyService
      - run: swag init --parseDependency --instanceName acme
      - run: cd ../BankService/server
      - run: swag init --parseDependency --instanceName bank
      - run: cd ../../FlightCompanyService
      - run: swag init --parseDependency --instanceName fc
      - run: cd ../GeoDistance
      - run: swag init --parseDependency --instanceName geo
      - run: mkdocs gh-deploy --force