name: gendocs

on:
  push:
    branches:
      - master 
      - main
      
permissions:
  contents: write
jobs:
  deploy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go-version: [ '1.21.x' ]

    steps:
      - uses: actions/checkout@v4
      - name: Setup Go ${{ matrix.go-version }}
        uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go-version }}
      # You can test your matrix by printing the current Go version
      - name: Display Go version
        run: go version
      - uses: actions/checkout@v4
      - name: Configure Git Credentials
        run: |
          git config user.name github-actions[bot]
          git config user.email 41898282+github-actions[bot]@users.noreply.github.com
      - uses: actions/setup-python@v5
        with:
          python-version: 3.x
      - run: echo "cache_id=$(date --utc '+%V')" >> $GITHUB_ENV 
      - uses: actions/cache@v4
        with:
          key: mkdocs-material-${{ env.cache_id }}
          path: .cache
          restore-keys: |
            mkdocs-material-
      - run: pip install -r requirements.txt
      - run: go install -v github.com/swaggo/swag/cmd/swag@latest
      - run: cd src/ACMESkyNCC/middleware
      - run: go mod tidy
      - run: swag init --parseDependency --instanceName ncc
      - run: cd ../../ACMESkyService
      - run: go mod tidy
      - run: swag init --parseDependency --instanceName acme
      - run: cd ../BankService/server
      - run: go mod tidy
      - run: swag init --parseDependency --instanceName bank
      - run: cd ../../FlightCompanyService
      - run: go mod tidy
      - run: swag init --parseDependency --instanceName fc
      - run: cd ../GeoDistance
      - run: go mod tidy
      - run: swag init --parseDependency --instanceName geo
      - run: mkdocs gh-deploy --force